#!/usr/bin/env bash
# mise description="Install project dependencies"
# mise depends=["pip:install", "ansible:install"]

if [ ! -f .vscode/settings.json ]
then
    echo "No .vscode/settings.json found, copying from mise template."
    mkdir -p .vscode
    cp .mise/templates/settings.json .vscode/settings.json
fi
